//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsWs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coureurs
    {
        public decimal dossard { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string nationalite { get; set; }
        public Nullable<System.DateTime> datenaissance { get; set; }
        public string equipe { get; set; }
    
        private equipes equipes { get; set; }
    }
}
